[package]
name = "rlox"
version = "0.1.0"
authors = ["Jeff Smith <jffreyjs@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "ast",
  "interpreter",
  "parser",
]

[dependencies]
ast = { path = "./ast" }
interpreter = { path = "./interpreter" }
parser = { path = "./parser" }
