[package]
name = "rlox"
version = "0.1.0"
authors = ["Jeff Smith <jsmith3@vonage.com>"]
edition = "2018"

[workspace]
members = [
  "ast",
  "interpreter"
]

[dependencies]
ast = { path = "./ast" }
interpreter = { path = "./interpreter" }
